default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
    -   id: docformatter
        args: ["--in-place"]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake
        args: ["--remove-all-unused-imports", "--in-place"]
-   repo: https://github.com/pycqa/isort
    rev: v5.11.3
    hooks:
      - id: isort
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/python-poetry/poetry
    rev: '1.3.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt","--without-hashes","--with","dev"]